In [1]:
import pydpeet as eet
import matplotlib.pyplot as plt

In [2]:
Data = eet.convert.convert_file(config = 'Neware', input_path = r"..\..\res\raw\Cal_Ageing_Checkup1.xlsx")
Data.head()

converting file to pandas DataFrame...
Reading sheets from ..\..\res\raw\Cal_Ageing_Checkup1.xlsx...
hadling record auxvol auxtemp sheets...
checking if headers need to be reindexed...
reindexing headers...
Handling sheets cycle, step and test...
merging cycle and step...
merging record and auxvol...
handling test sheet...
merging cycle_step_test and test...
checking if headers need to be reindexed...
reindexing headers...
merging record_auxvol and auxtemp...
handling final merge...

D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\zyklisierer\neware\reader.py:280: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_auxvol.rename(columns={'Date': 'Date - auxVol', 'DataPoint': 'DataPoint - auxVol'}, inplace=True)
D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\zyklisierer\neware\reader.py:286: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_auxtemp.rename(columns={'Date': 'Date - auxTemp', 'DataPoint': 'DataPoint - auxTemp'}, inplace=True)

mapping columns...
 WARNING: Missing column: 'EISFreq[Hz]'. Adding Collumn (with None values) named: 'EISFreq[Hz]'.
 WARNING: Missing column: 'Zre[Ohm]'. Adding Collumn (with None values) named: 'Zre[Ohm]'.
 WARNING: Missing column: 'Zim[Ohm]'. Adding Collumn (with None values) named: 'Zim[Ohm]'.
 WARNING: Missing column: 'DC_Current[A]'. Adding Collumn (with None values) named: 'DC_Current[A]'.
dropping additional data...
adding metadata to Dataframe...
Getting columns in correct order...
Checking for duplicate extra columns...
Selecting and ordering standard columns...
Selecting extra columns...
Combining standard and extra columns...
Reordered DataFrame columns!
Starting to fix data format...
Using formatter for config: Config.Neware
Data format fixed.
convert_file executed in 4.405235 seconds

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],DC_Current[A]
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,None
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,None
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,None
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,None
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,None

In [3]:
Data_segmented = eet.process.sequence.step_analyzer_primitives(Data)
Data_segmented.head()

Input Warning: Using EXAMPLE_STEP_ANALYZER_PRIMITIVES_CONFIG as fallback configuration. Manual Parameters will be kept.
Input Warning: Dropping NaN values in 'Testtime[s]', dropping duplicates and sorting 'Testtime[s]' column.
    0.3079s precompiling step_analyzer_primitives and df_primitives_correction
detecting segments in dataframe of size 163770...
    0.0009s calculating Power[W]
    0.0010s separating Voltage[V] into segments using incremental linear fit
    0.0008s separating Current[A] into segments using incremental linear fit
    0.0009s separating Power[W] into segments using incremental linear fit
    0.0012s adding Length_Segment_Voltage[V] to calculate the dominating segments
    0.0014s adding Length_Segment_Current[A] to calculate the dominating segments
    0.0013s adding Length_Segment_Power[W] to calculate the dominating segments
    0.0037s suppressing smaller segments
    0.0175s attempting to merge neighboring segments
    WARNING: Removed segments during finetuning of the width in 'Segment_Current[A]': 11:9111, 43678:44495 ...
    WARNING: Removed segments during finetuning of the width in 'Segment_Power[W]': 5:10
    0.0391s fine tuning width of constant segments to better fit the data
starting annotation...
    0.0021s adding ID annotation
    0.0066s adding variable annotation
    0.1152s adding duration, length, min, max, avg, type, direction, slope annotation
    0.0096s dropping temporary length and segment columns
starting additional data checks and corrections...
    0.0119s checking CV Segments that end with 0A
    WARNING: Suspicious Voltage Segments that end with Current[A] = 0.0 found.
    Turned into CC segments: [(np.int64(1), (11522.9, 11581.9)), (np.int64(4), (29911.8, 29970.8))], ...
    0.0704s correcting CV Segments that end with 0A
    0.0004s checking zero length segments
    0.0179s correcting zero length segments
    0.0132s checking Power segments with 0W
    0.0056s correcting Power segments with 0W
    0.1041s updating annotations

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],...,ID,Variable,Duration,Length,Min,Max,Avg,Type,Direction,Slope
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074

In [4]:
Battery_Config = eet.process.analyze.am23nmc
method = eet.process.analyze.SocMethod.WITHOUT_RESET

# todo: is it possible to probide acces to the Batemo/About-Energy database and fetch battery configs directly from there?
# todo: or we download it and provide the databse directly?

Result = eet.process.analyze.add_soc(
    df=Data,
    df_primitives=Data_segmented,
    standard_method=method,
    config=Battery_Config
)
Result.head()

analyzing segments...
    0.0030s filtering by ID
    0.0037s tag simple segments
    0.0058s tag sequences
    0.0606s assign longest sequence
    0.0005s separate sequences and df_with_segments
 Input Warning: Using default standard columns: ['Testtime[s]', 'Voltage[V]', 'Current[A]', 'Power[W]']
 Input Warning: Using default standard columns: ['Testtime[s]', 'Voltage[V]', 'Current[A]', 'Power[W]']

D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\analyze\calculations\soc_methods.py:191: UserWarning: Column 'Capacity[Ah]' missing, adding with function add_capacity.
  warnings.warn("Column 'Capacity[Ah]' missing, adding with function add_capacity.")

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],DC_Current[A],Capacity[Ah],SOC
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,None,NaN,0.000000
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,None,NaN,0.000083
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,None,NaN,0.000167
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,None,NaN,0.000250
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,None,NaN,0.000333