In [1]:
import pydpeet as eet
import matplotlib.pyplot as plt
eet.utils.set_logging_style("WARNING")

In [2]:
Data = eet.convert.convert_file(config = 'Neware', input_path = r"..\..\res\raw\Cal_Ageing_Checkup1.xlsx")
Data.head()

D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\zyklisierer\neware\reader.py:281: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_auxvol.rename(columns={'Date': 'Date - auxVol', 'DataPoint': 'DataPoint - auxVol'}, inplace=True)
D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\zyklisierer\neware\reader.py:287: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_auxtemp.rename(columns={'Date': 'Date - auxTemp', 'DataPoint': 'DataPoint - auxTemp'}, inplace=True)
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\map.py:47 | Missing column: 'EISFreq[Hz]'. Adding Collumn (with None values) named: 'EISFreq[Hz]'.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\map.py:47 | Missing column: 'Zre[Ohm]'. Adding Collumn (with None values) named: 'Zre[Ohm]'.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\map.py:47 | Missing column: 'Zim[Ohm]'. Adding Collumn (with None values) named: 'Zim[Ohm]'.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\convert\map.py:47 | Missing column: 'DC_Current[A]'. Adding Collumn (with None values) named: 'DC_Current[A]'.

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],DC_Current[A]
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,None
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,None
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,None
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,None
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,None

In [3]:
Data_segmented = eet.process.sequence.step_analyzer_primitives(Data)
Data_segmented.head()

WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\step_analyzer.py:131 | Using EXAMPLE_STEP_ANALYZER_PRIMITIVES_CONFIG as fallback configuration. Manual Parameters will be kept.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\step_analyzer.py:166 | Dropping NaN values in 'Testtime[s]', dropping duplicates and sorting 'Testtime[s]' column.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\processing\widen_constant_segments.py:157 | Removed segments during finetuning of the width in 'Segment_Current[A]': 11:9111, 43678:44495 ...
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\processing\widen_constant_segments.py:159 | Removed segments during finetuning of the width in 'Segment_Power[W]': 5:10
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\processing\check_CV_results.py:208 | Suspicious Voltage Segments that end with Current[A] = 0.0 found.
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\processing\check_CV_results.py:214 | Turned into CC segments: [(np.int64(1), (11522.9, 11581.9)), (np.int64(4), (29911.8, 29970.8))], ...

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],...,ID,Variable,Duration,Length,Min,Max,Avg,Type,Direction,Slope
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,...,1,V,9112,9111.0,3.5269,4.2001,3.889836,Ramp,Up,0.000074

In [4]:
Battery_Config = eet.process.analyze.am23nmc
method = eet.process.analyze.SocMethod.WITHOUT_RESET

# todo: is it possible to probide acces to the Batemo/About-Energy database and fetch battery configs directly from there?
# todo: or we download it and provide the databse directly?

Result = eet.process.analyze.add_soc(
    df=Data,
    df_primitives=Data_segmented,
    standard_method=method,
    config=Battery_Config
)
Result.head()

D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\analyze\calculations\soc_methods.py:190: UserWarning: Column 'Capacity[Ah]' missing, adding with function add_capacity.
  warnings.warn("Column 'Capacity[Ah]' missing, adding with function add_capacity.")
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\postprocessing\filter_df.py:145 | Using default standard columns:
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\postprocessing\filter_df.py:146 | ['Testtime[s]', 'Voltage[V]', 'Current[A]', 'Power[W]']
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\postprocessing\filter_df.py:145 | Using default standard columns:
WARNING | D:\Coding\PyDPEET_BA\pythonProject\pydpeet\src\pydpeet\process\sequence\utils\postprocessing\filter_df.py:146 | ['Testtime[s]', 'Voltage[V]', 'Current[A]', 'Power[W]']

,Metadata,StepID,Voltage[V],Current[A],Temperature[°C],Testtime[s],Absolute Time[yyyy-mm-dd hh:mm:ss],EISFreq[Hz],Zre[Ohm],Zim[Ohm],DC_Current[A],Capacity[Ah],SOC
0.0,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx U...,0,3.5269,1.4378,27.8,0.0,2024-02-01 10:09:04,None,None,None,None,NaN,0.000000
1.0,None,0,3.5287,1.4398,27.8,1.0,2024-02-01 10:09:05,None,None,None,None,NaN,0.000083
2.0,None,0,3.5298,1.4400,27.8,2.0,2024-02-01 10:09:06,None,None,None,None,NaN,0.000167
3.0,None,0,3.5307,1.4400,27.8,3.0,2024-02-01 10:09:07,None,None,None,None,NaN,0.000250
4.0,None,0,3.5315,1.4401,27.8,4.0,2024-02-01 10:09:08,None,None,None,None,NaN,0.000333